/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ConnectionModel;
import util.ConnectionHistory;
import util.Database;
import util.DatabaseTools;
import util.SQLConnection;

/**
 *
 * @author boulhol
 */
public class FrameLogin extends javax.swing.JFrame
{

    private ConnectionModel m_connectionModel;

    /**
     * Creates new form Login
     */
    public FrameLogin()
    {
	m_connectionModel = new ConnectionModel();
	initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabelLogin = new javax.swing.JLabel();
        jComboBoxLogin = new javax.swing.JComboBox<>();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelDatabase = new javax.swing.JLabel();
        jComboBoxDatabase = new javax.swing.JComboBox<>();
        jButtonConnection = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connexion");
        setBounds(new java.awt.Rectangle(0, 0, 450, 350));
        addWindowListener(formListener);

        jLabelLogin.setText("Nom d'utilisateur");

        jComboBoxLogin.setEditable(true);
        jComboBoxLogin.setModel(m_connectionModel.getUserModel());

        jLabelPassword.setLabelFor(jComboBoxLogin);
        jLabelPassword.setText("Mot de passe");

        jLabelDatabase.setText("Base de données");

        jComboBoxDatabase.setEditable(true);
        jComboBoxDatabase.setModel(m_connectionModel.getDatabaseModel());
        jComboBoxDatabase.setEditor(new editor.ComboBoxDatabaseEditor(m_connectionModel.getSelectedDatabase()));

        jButtonConnection.setText("Connexion");
        jButtonConnection.addActionListener(formListener);

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/cross-piston.svg.med.png"))); // NOI18N
        jLabelLogo.setAlignmentX(0.5F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLogin)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBoxLogin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPassword)
                        .addGap(26, 26, 26)
                        .addComponent(jPasswordField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDatabase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDatabase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConnection))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jComboBoxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatabase)
                    .addComponent(jComboBoxDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonConnection)
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.WindowListener
    {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            if (evt.getSource() == jButtonConnection)
            {
                FrameLogin.this.jButtonConnectionActionPerformed(evt);
            }
        }

        public void windowActivated(java.awt.event.WindowEvent evt)
        {
        }

        public void windowClosed(java.awt.event.WindowEvent evt)
        {
        }

        public void windowClosing(java.awt.event.WindowEvent evt)
        {
            if (evt.getSource() == FrameLogin.this)
            {
                FrameLogin.this.formWindowClosing(evt);
            }
        }

        public void windowDeactivated(java.awt.event.WindowEvent evt)
        {
        }

        public void windowDeiconified(java.awt.event.WindowEvent evt)
        {
        }

        public void windowIconified(java.awt.event.WindowEvent evt)
        {
        }

        public void windowOpened(java.awt.event.WindowEvent evt)
        {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConnectionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonConnectionActionPerformed
    {//GEN-HEADEREND:event_jButtonConnectionActionPerformed
	Database db = (Database) m_connectionModel.getDatabaseModel().getSelectedItem();
	String user = (String) m_connectionModel.getUserModel().getSelectedItem();
	String password = new String(jPasswordField.getPassword());
	if (db != null && user != null && db.getName().length() > 0 && db.getUrl().length() > 0 && user.length() > 0)
	{
	    Connection master = SQLConnection.getMasterConnection(db.getUrl(), user, password);
	    if (master == null)
	    {
		JOptionPane.showMessageDialog(this, "Erreur de connexion. vérifiez les paramètres", "Erreur de connexion", JOptionPane.ERROR_MESSAGE);
	    } else if (util.DatabaseTools.databaseExists(master, db.getName()))
	    {
		try
		{
		    master.close();
		} catch (SQLException e)
		{
		}

		SQLConnection.setup(db.getUrl(), db.getName(), user, password);

		Connection conn = SQLConnection.getConnection();
		if (conn != null)
		{
		    if (util.DatabaseTools.checkDatabase())
		    {
			redirectToFrame(util.DatabaseTools.getRole());
			// si la connexion est réussie, on l'ajoute à l'historique des connexions.
			ConnectionHistory.getInstance().add(db, user);
		    } else
		    {
			JOptionPane.showMessageDialog(this, "La base de données est invalide ou corrompue", "Erreur de connexion", JOptionPane.ERROR_MESSAGE);
		    }
		} else
		{
		    JOptionPane.showMessageDialog(this, "Erreur de connexion. Vous ne disposez peut-être pas des autorisations nécessaires", "Erreur de connexion", JOptionPane.ERROR_MESSAGE);
		}
	    } else
	    {
		int answer = JOptionPane.showConfirmDialog(this, String.format("La base de données %s n'existe pas. désirez-vous la créer?", db.getName()), "Base de donnée inexistante", JOptionPane.YES_NO_OPTION);
		if (answer == JOptionPane.YES_OPTION)
		{
		    SQLConnection.setup(db.getUrl(), db.getName(), user, password);
		    if (util.DatabaseTools.installDatabase(db.getUrl(), db.getName(), user, password))
		    {
			JOptionPane.showMessageDialog(this, "Base de donnée installée avec succès");
		    }
		    else
		    {
			JOptionPane.showMessageDialog(this, "Une erreur est survenue lors de l'installation de la base de données", "Erreur d'installation", JOptionPane.ERROR_MESSAGE);
		    }
		    // rediriger sur la fenetre gestion users
		    redirectToFrame(util.DatabaseTools.getRole());
		}
	    }
	} else
	{
	    JOptionPane.showMessageDialog(this, "Des champs requis sont manquants", "Erreur de connexion", JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_jButtonConnectionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
	ConnectionHistory.getInstance().save();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnection;
    private javax.swing.JComboBox<util.Database> jComboBoxDatabase;
    private javax.swing.JComboBox<String> jComboBoxLogin;
    private javax.swing.JLabel jLabelDatabase;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables

    /**
     * ouvre la fenetre correspondant au rôle donné
     * @param role le role pour lequel ouvrir la fenêtre
     */
    private void redirectToFrame(String role)
    {
	if (role != null)
	{
	    JFrame f;
	    JOptionPane.showMessageDialog(this, String.format("Connexion réussie, bienvenue %s %s", role, SQLConnection.getUser()), "Connexion réussie", JOptionPane.INFORMATION_MESSAGE);
	    switch (role)
	    {
		case "db_owner":
		    f = new FrameGestionUser();
		    break;
		default:
		    f = null;
	    }
	    
	    if (f != null)
	    {
		f.addWindowListener(new SubWindowClosingListener());
		setVisible(false);
		f.setVisible(true);
	    }
	}
    }
    
    private class SubWindowClosingListener extends WindowAdapter
    {
	@Override
	public void windowClosing(WindowEvent e)
	{
	    FrameLogin.this.setVisible(true);
	}
    }
}
