/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ManagerDatabaseUser;
import entity.DatabaseUser;
import javax.swing.JOptionPane;
import model.ComboBoxUserModel;
import util.ReturnDataBase;

/**
 *
 * @author brun
 */
public class FrameGestionUser extends javax.swing.JFrame
{

    /**
     * Creates new form FrameGestionUser
     */
    public FrameGestionUser()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelUser = new javax.swing.JLabel();
        labelRole = new javax.swing.JLabel();
        comboBoxRole = new javax.swing.JComboBox();
        buttonSupprimerUser = new javax.swing.JButton();
        buttonAffecter = new javax.swing.JButton();
        labelTraiterUser = new javax.swing.JLabel();
        comboBoxUser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Utilisateur");

        labelUser.setText("User");
        labelUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRole.setText("Rôle");

        comboBoxRole.setModel(new model.ComboBoxRoleModel());
        comboBoxRole.setSelectedIndex(0);

        buttonSupprimerUser.setText("Supprimer l'Utilisateur");
        buttonSupprimerUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonSupprimerUserActionPerformed(evt);
            }
        });

        buttonAffecter.setText("Affecter le Rôle");
        buttonAffecter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonAffecterActionPerformed(evt);
            }
        });

        labelTraiterUser.setText("Taiter un Utilisateur");

        comboBoxUser.setEditable(true);
        comboBoxUser.setModel(new model.ComboBoxUserModel());
        comboBoxUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboBoxUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(labelRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxRole, 0, 163, Short.MAX_VALUE)
                    .addComponent(comboBoxUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(buttonAffecter)
                .addGap(18, 18, 18)
                .addComponent(buttonSupprimerUser)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(labelTraiterUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelTraiterUser)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUser)
                    .addComponent(comboBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRole)
                    .addComponent(comboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSupprimerUser)
                    .addComponent(buttonAffecter))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAffecterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonAffecterActionPerformed
    {//GEN-HEADEREND:event_buttonAffecterActionPerformed
        DatabaseUser dbu = new DatabaseUser((String)comboBoxUser.getSelectedItem(), (String)comboBoxRole.getSelectedItem());
	ReturnDataBase ret = ManagerDatabaseUser.updateDatabaseUser(dbu);
	if (ret.getCode() == 0)
	{
	    ((ComboBoxUserModel)comboBoxUser.getModel()).setUser(dbu);
	    JOptionPane.showMessageDialog(this, "Utilisateur " + dbu + " mis à jour avec succès.", "Mise à jour utilisateur", JOptionPane.INFORMATION_MESSAGE);
	}
	else
	{
	    JOptionPane.showMessageDialog(this, "Une erreur est survenue : " + ret, "Mise à jour d'utilisateur", JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_buttonAffecterActionPerformed

    private void comboBoxUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboBoxUserActionPerformed
    {//GEN-HEADEREND:event_comboBoxUserActionPerformed
        String role = ((ComboBoxUserModel)comboBoxUser.getModel()).getSelectedRole();
	if (role != null)
	{
	    comboBoxRole.setSelectedItem(role);
	}
    }//GEN-LAST:event_comboBoxUserActionPerformed

    private void buttonSupprimerUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonSupprimerUserActionPerformed
    {//GEN-HEADEREND:event_buttonSupprimerUserActionPerformed
        String user = (String)comboBoxUser.getSelectedItem();
	ReturnDataBase ret = ManagerDatabaseUser.deleteDatabaseUser(user);
	if (ret.getCode() == 0)
	{
	    ((ComboBoxUserModel)comboBoxUser.getModel()).removeUser(user);
	    JOptionPane.showMessageDialog(this, "L'utilisateur " + user + " a été supprimé.", "Suppresionn d'utilisateur", JOptionPane.INFORMATION_MESSAGE);
	}
	else
	{
	    JOptionPane.showMessageDialog(this, "Une erreur est survenur : " + ret, "Suppression d'utilisateur", JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_buttonSupprimerUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrameGestionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrameGestionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrameGestionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrameGestionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrameGestionUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAffecter;
    private javax.swing.JButton buttonSupprimerUser;
    private javax.swing.JComboBox comboBoxRole;
    private javax.swing.JComboBox<String> comboBoxUser;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelTraiterUser;
    private javax.swing.JLabel labelUser;
    // End of variables declaration//GEN-END:variables
}
