/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author denis
 */
public class FrameResponsableApplication extends javax.swing.JFrame {

    /**
     * Creates new form FrameResponsableAppllication
     */
    public FrameResponsableApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneResponsableApplication = new javax.swing.JTabbedPane();
        panelCategories = new javax.swing.JPanel();
        labelCategories = new javax.swing.JLabel();
        labelPetit = new javax.swing.JLabel();
        labelMoyen = new javax.swing.JLabel();
        labelGrand = new javax.swing.JLabel();
        labelSuperieur = new javax.swing.JLabel();
        labelInferieur1 = new javax.swing.JLabel();
        textfieldToleranceInferieureMoyen = new javax.swing.JTextField();
        textfieldToleranceInferieurePetit = new javax.swing.JTextField();
        textfieldToleranceInferieureGrand = new javax.swing.JTextField();
        textfieldToleranceSuperieureMoyen = new javax.swing.JTextField();
        textfieldToleranceSuperieureGrand = new javax.swing.JTextField();
        textfieldToleranceSuperieurePetit = new javax.swing.JTextField();
        buttonEnregistrerCategories = new javax.swing.JButton();
        buttonReinitialiserCategories = new javax.swing.JButton();
        panelMachines = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JList listeMachines = new javax.swing.JList();
        labelCreerMachine = new javax.swing.JLabel();
        textfieldNomMachineACreer = new javax.swing.JTextField();
        buttonCreerMachine = new javax.swing.JButton();
        buttonReinitialiserMachine = new javax.swing.JButton();
        buttonEnregistrerMachine = new javax.swing.JButton();
        labelNomMachine = new javax.swing.JLabel();
        panelModele = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        javax.swing.JList listeModeles = new javax.swing.JList();
        textfieldNomModele = new javax.swing.JTextField();
        labelCreerModele = new javax.swing.JLabel();
        buttonCreerModifierModele = new javax.swing.JButton();
        labelNomModele = new javax.swing.JLabel();
        labelDiametre = new javax.swing.JLabel();
        textfieldDiametre = new javax.swing.JTextField();
        buttonReinitialiserModele = new javax.swing.JButton();
        buttonEnregistrerModele = new javax.swing.JButton();
        buttonRetour = new javax.swing.JButton();
        buttonValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion d'application");

        tabbedPaneResponsableApplication.setName(""); // NOI18N

        labelCategories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCategories.setText("Catégories");

        labelPetit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPetit.setText("Petit");

        labelMoyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMoyen.setText("Moyen");

        labelGrand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGrand.setText("Grand");

        labelSuperieur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSuperieur.setText("Tolérance supérieure");

        labelInferieur1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInferieur1.setText("Tolérance inférieure");

        textfieldToleranceInferieureMoyen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfieldToleranceInferieureMoyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldToleranceInferieureMoyenActionPerformed(evt);
            }
        });

        textfieldToleranceInferieurePetit.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textfieldToleranceInferieureGrand.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textfieldToleranceSuperieureMoyen.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textfieldToleranceSuperieureGrand.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textfieldToleranceSuperieurePetit.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buttonEnregistrerCategories.setText("Enregistrer");

        buttonReinitialiserCategories.setText("Réinitialiser");

        javax.swing.GroupLayout panelCategoriesLayout = new javax.swing.GroupLayout(panelCategories);
        panelCategories.setLayout(panelCategoriesLayout);
        panelCategoriesLayout.setHorizontalGroup(
            panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCategoriesLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textfieldToleranceInferieurePetit)
                        .addComponent(labelInferieur1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                    .addComponent(textfieldToleranceInferieureMoyen, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldToleranceInferieureGrand, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonReinitialiserCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(buttonEnregistrerCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(labelGrand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMoyen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPetit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addGap(107, 107, 107)
                .addGroup(panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSuperieur, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldToleranceSuperieureMoyen, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldToleranceSuperieureGrand, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldToleranceSuperieurePetit, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
        panelCategoriesLayout.setVerticalGroup(
            panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriesLayout.createSequentialGroup()
                .addGroup(panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCategoriesLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelInferieur1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSuperieur, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCategoriesLayout.createSequentialGroup()
                                .addComponent(textfieldToleranceInferieurePetit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfieldToleranceInferieureMoyen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfieldToleranceInferieureGrand, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCategoriesLayout.createSequentialGroup()
                                .addComponent(textfieldToleranceSuperieurePetit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfieldToleranceSuperieureMoyen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfieldToleranceSuperieureGrand, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCategoriesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(labelPetit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMoyen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelGrand, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEnregistrerCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonReinitialiserCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneResponsableApplication.addTab("Catégories", panelCategories);

        jScrollPane1.setViewportView(listeMachines);

        labelCreerMachine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCreerMachine.setText("Créer une nouvelle machine");

        buttonCreerMachine.setText("Créer");

        buttonReinitialiserMachine.setText("Réinitialiser");

        buttonEnregistrerMachine.setText("Enregistrer");

        labelNomMachine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomMachine.setText("Nom :");

        javax.swing.GroupLayout panelMachinesLayout = new javax.swing.GroupLayout(panelMachines);
        panelMachines.setLayout(panelMachinesLayout);
        panelMachinesLayout.setHorizontalGroup(
            panelMachinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMachinesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelMachinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMachinesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCreerMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(panelMachinesLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(panelMachinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCreerMachine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelMachinesLayout.createSequentialGroup()
                                .addGroup(panelMachinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonReinitialiserMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonEnregistrerMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelMachinesLayout.createSequentialGroup()
                                        .addComponent(labelNomMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textfieldNomMachineACreer, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 117, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelMachinesLayout.setVerticalGroup(
            panelMachinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMachinesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMachinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMachinesLayout.createSequentialGroup()
                        .addComponent(labelCreerMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(panelMachinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfieldNomMachineACreer, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(labelNomMachine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(panelMachinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMachinesLayout.createSequentialGroup()
                                .addComponent(buttonCreerMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 225, Short.MAX_VALUE))
                            .addGroup(panelMachinesLayout.createSequentialGroup()
                                .addComponent(buttonEnregistrerMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonReinitialiserMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        tabbedPaneResponsableApplication.addTab("Machines", panelMachines);

        jScrollPane2.setViewportView(listeModeles);

        labelCreerModele.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCreerModele.setText("Créer un nouveau modèle");

        buttonCreerModifierModele.setText("Créer");

        labelNomModele.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomModele.setText("Nom :");

        labelDiametre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDiametre.setText("Diamètre :");

        buttonReinitialiserModele.setText("Réinitialiser");

        buttonEnregistrerModele.setText("Enregistrer");

        javax.swing.GroupLayout panelModeleLayout = new javax.swing.GroupLayout(panelModele);
        panelModele.setLayout(panelModeleLayout);
        panelModeleLayout.setHorizontalGroup(
            panelModeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModeleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelModeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModeleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                        .addComponent(buttonCreerModifierModele, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(panelModeleLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(panelModeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModeleLayout.createSequentialGroup()
                                .addGroup(panelModeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelDiametre, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(labelNomModele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelModeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textfieldDiametre, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(textfieldNomModele))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelModeleLayout.createSequentialGroup()
                                .addComponent(labelCreerModele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(panelModeleLayout.createSequentialGroup()
                                .addGroup(panelModeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonEnregistrerModele, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonReinitialiserModele, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        panelModeleLayout.setVerticalGroup(
            panelModeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModeleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelModeleLayout.createSequentialGroup()
                        .addComponent(labelCreerModele, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(panelModeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfieldNomModele, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(labelNomModele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelModeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDiametre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldDiametre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(buttonCreerModifierModele, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(buttonEnregistrerModele, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonReinitialiserModele, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tabbedPaneResponsableApplication.addTab("Modèles", panelModele);

        buttonRetour.setText("Retour");

        buttonValider.setText("Valider");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPaneResponsableApplication)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tabbedPaneResponsableApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRetour, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(buttonValider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldToleranceInferieureMoyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldToleranceInferieureMoyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldToleranceInferieureMoyenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameResponsableApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameResponsableApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameResponsableApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameResponsableApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameResponsableApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreerMachine;
    private javax.swing.JButton buttonCreerModifierModele;
    private javax.swing.JButton buttonEnregistrerCategories;
    private javax.swing.JButton buttonEnregistrerMachine;
    private javax.swing.JButton buttonEnregistrerModele;
    private javax.swing.JButton buttonReinitialiserCategories;
    private javax.swing.JButton buttonReinitialiserMachine;
    private javax.swing.JButton buttonReinitialiserModele;
    private javax.swing.JButton buttonRetour;
    private javax.swing.JButton buttonValider;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCategories;
    private javax.swing.JLabel labelCreerMachine;
    private javax.swing.JLabel labelCreerModele;
    private javax.swing.JLabel labelDiametre;
    private javax.swing.JLabel labelGrand;
    private javax.swing.JLabel labelInferieur1;
    private javax.swing.JLabel labelMoyen;
    private javax.swing.JLabel labelNomMachine;
    private javax.swing.JLabel labelNomModele;
    private javax.swing.JLabel labelPetit;
    private javax.swing.JLabel labelSuperieur;
    private javax.swing.JPanel panelCategories;
    private javax.swing.JPanel panelMachines;
    private javax.swing.JPanel panelModele;
    private javax.swing.JTabbedPane tabbedPaneResponsableApplication;
    private javax.swing.JTextField textfieldDiametre;
    private javax.swing.JTextField textfieldNomMachineACreer;
    private javax.swing.JTextField textfieldNomModele;
    private javax.swing.JTextField textfieldToleranceInferieureGrand;
    private javax.swing.JTextField textfieldToleranceInferieureMoyen;
    private javax.swing.JTextField textfieldToleranceInferieurePetit;
    private javax.swing.JTextField textfieldToleranceSuperieureGrand;
    private javax.swing.JTextField textfieldToleranceSuperieureMoyen;
    private javax.swing.JTextField textfieldToleranceSuperieurePetit;
    // End of variables declaration//GEN-END:variables
    
    
    /**
     * Cette méthode permet d'afficher dans les champs texte les dimenstions des catégories 
     * stockés dans la base de donnée
     */
    private void setCategorie()
    {
        Categorie c =  ManagerCategorie.getCategorie("Petit");
        textfieldToleranceInferieurePetit.setText("" + c.getMinCategorie());
        textfieldToleranceSuperieurePetit.setText("" + c.getMaxCategorie());

         c =  ManagerCategorie.getCategorie("Moyen");
        textfieldToleranceInferieureMoyen.setText("" + c.getMinCategorie());
        textfieldToleranceSuperieureMoyen.setText("" + c.getMaxCategorie());

         c =  ManagerCategorie.getCategorie("Grand");
        textfieldToleranceInferieureGrand.setText("" + c.getMinCategorie());
        textfieldToleranceSuperieureGrand.setText("" + c.getMaxCategorie());       
    }
}
