/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Lot;
import javax.swing.JOptionPane;
import model.ModelComboModele;
import dao.ManagerLot;
import dao.ManagerModele;
import dao.ManagerStock;
import java.util.ArrayList;
import util.ReturnDataBase;

/**
 *
 * @author denis
 */
public class PopupLancerNouveauLot extends javax.swing.JDialog
{

    /**
     * Creates new form PopupLancerNouveauLot
     */
    public PopupLancerNouveauLot(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        comboboxModeles = new javax.swing.JComboBox();
        labelModele = new javax.swing.JLabel();
        labelQuantite = new javax.swing.JLabel();
        textfieldQuantite = new javax.swing.JTextField();
        labelQuantiteProduction = new javax.swing.JLabel();
        labelQuantiteStock = new javax.swing.JLabel();
        labelQuantiteProductionNombre = new javax.swing.JLabel();
        labelQuantiteStockNombre = new javax.swing.JLabel();
        buttonLancerLot = new javax.swing.JButton();
        buttonRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lancer un nouveau lot");

        comboboxModeles.setModel(new ModelComboModele());
        comboboxModeles.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboboxModelesActionPerformed(evt);
            }
        });

        labelModele.setText("Modèle :");

        labelQuantite.setText("Quantité :");

        labelQuantiteProduction.setText("Quantité en production :");

        labelQuantiteStock.setText("Quantité en stock :");

        buttonLancerLot.setText("Lancer le lot");
        buttonLancerLot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonLancerLotActionPerformed(evt);
            }
        });

        buttonRetour.setText("Retour");
        buttonRetour.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelModele, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboboxModeles, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textfieldQuantite))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelQuantiteStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelQuantiteProduction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelQuantiteProductionNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelQuantiteStockNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonLancerLot, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(buttonRetour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelQuantite, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(labelModele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonLancerLot, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(comboboxModeles)
                    .addComponent(textfieldQuantite))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonRetour, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(labelQuantiteProductionNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelQuantiteProduction, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelQuantiteStock, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(labelQuantiteStockNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLancerLotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonLancerLotActionPerformed
    {//GEN-HEADEREND:event_buttonLancerLotActionPerformed
        ReturnDataBase retour;
        Lot lot = recupereLot();
        retour = ManagerLot.lancerLot(lot);
        if (retour.getCode() == 0)
        {
            JOptionPane.showMessageDialog(this, retour.getMessage());
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Code = " + retour.getCode() + "\nMessage = " + retour.getMessage());
        }
    }//GEN-LAST:event_buttonLancerLotActionPerformed

    private void buttonRetourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonRetourActionPerformed
    {//GEN-HEADEREND:event_buttonRetourActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonRetourActionPerformed

    private void comboboxModelesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboboxModelesActionPerformed
    {//GEN-HEADEREND:event_comboboxModelesActionPerformed
        labelQuantiteProductionNombre.setText(ManagerModele.getQuantiteEnProd(comboboxModeles.getSelectedItem().toString()) + " pièces");
        labelQuantiteStockNombre.setText(ManagerStock.getQuantiteEnStock(comboboxModeles.getSelectedItem().toString()) + " caisses");
    }//GEN-LAST:event_comboboxModelesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PopupLancerNouveauLot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PopupLancerNouveauLot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PopupLancerNouveauLot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PopupLancerNouveauLot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                PopupLancerNouveauLot dialog = new PopupLancerNouveauLot(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLancerLot;
    private javax.swing.JButton buttonRetour;
    private javax.swing.JComboBox comboboxModeles;
    private javax.swing.JLabel labelModele;
    private javax.swing.JLabel labelQuantite;
    private javax.swing.JLabel labelQuantiteProduction;
    private javax.swing.JLabel labelQuantiteProductionNombre;
    private javax.swing.JLabel labelQuantiteStock;
    private javax.swing.JLabel labelQuantiteStockNombre;
    private javax.swing.JTextField textfieldQuantite;
    // End of variables declaration//GEN-END:variables

    public Lot recupereLot()
    {
        Lot lot = new Lot();
        lot.setIdModele((String) comboboxModeles.getSelectedItem());
        if (util.Tools.estInt(textfieldQuantite.getText()))
        {
            lot.setNbrPieceDemande(Integer.parseInt(textfieldQuantite.getText()));
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Quantité Incorrecte");
        }
        
        return lot;
    }
}
